### ISSUE TITLE
Side bars do not behave correctly

### ISSUE THREAD

**Issue by Yookiop** [deathbeam/example-plugin#35] opened 2024-02-25 20:55 UTC
![Naamloos](https://github.com/deathbeam/example-plugin/assets/157283452/23361bfa-1f15-44e8-b2df-e6371431de86)
Easiest suggestion is to maybe make the bar between chat & inventory wider (see picture below), so that dark balk is in front of the weird behaving balk and the problem isn't visible anymore:
![Naamloo1s](https://github.com/deathbeam/example-plugin/assets/157283452/8f556dfe-0928-4a94-ba4b-5d09c9f1cd0f)

**Comment by deathbeam** [comment] 2024-02-25 21:51
Duplicate of #12

**Closed by deathbeam** 2024-02-25 21:51 UTC

**Comment by Yookiop** [comment] 2024-02-25 22:32
@deathbeam thanks for updating the issue, however I see that the duplicated issue is around 2,5 years old and still open. This makes me feel like it's not being fixed, can we try to help fixing the issue with other runelite plugin developers support? I love the plugin you made though, but this bug is very annoying

**Comment by deathbeam** [comment] 2024-02-25 22:53
> @deathbeam thanks for updating the issue, however I see that the duplicated issue is around 2,5 years old and still open. This makes me feel like it's not being fixed, can we try to help fixing the issue with other runelite plugin developers support? I love the plugin you made though, but this bug is very annoying

Yea I never got to fixing it as I dont really play OSRS anymore. I might look at it at some point tho if I will be bored but cant make any promises

**Comment by Yookiop** [comment] 2024-02-25 23:29
@deathbeam Can I or others also contribute to this plugin? I would want to try and fix it but github and java is still pretty new to me. I could also ask plugin developers in the Runelite discord that maybe are willing to fix it. Ive spoken some people that are not using this plugin due the bug, I could imagine that some experienced developer is willing to fix it

**Comment by deathbeam** [comment] 2024-02-26 01:36
> @deathbeam Can I or others also contribute to this plugin? I would want to try and fix it but github and java is still pretty new to me. I could also ask plugin developers in the Runelite discord that maybe are willing to fix it. Ive spoken some people that are not using this plugin due the bug, I could imagine that some experienced developer is willing to fix it

Well its open source and pull requests are enabled so sure, I can review it after.

**Comment by Yookiop** [comment] 2024-04-11 02:26
@deathbeam please fix 😔
