### ISSUE TITLE
Tooltips sticking onto right side of deleted chatbox

### ISSUE THREAD

**Issue by nomadicvice** [deathbeam/example-plugin#26] opened 2023-07-31 01:04 UTC
Basically if your tooltip bleeds over to the right side of the where the chatbox would normally be (between chatbox and your inventory), it'll cause part of the tooltip to stick onto that little section. This gets cleared after opening and re-closing your chatbox but is still visually annoying.

1) Example of stuck tooltips (see bottom right): https://i.imgur.com/bJfCOsN.png
2) Opening chatbox to clean the issue: https://i.imgur.com/l1GnofR.png
3) Re-closing chatbox: https://i.imgur.com/t1AelTU.png

**Comment by nomadicvice** [comment] 2023-07-31 01:06
Was looking at open tickets and saw this was already addressed a long time ago https://github.com/deathbeam/example-plugin/issues/12

**Comment by deathbeam** [comment] 2024-02-25 21:51
Duplicate of #12 indeed

**Closed by deathbeam** 2024-02-25 21:51 UTC
