### ISSUE TITLE
Private messages are randomly going up and down sometimes

### ISSUE THREAD

**Issue by Razvanu7z** [deathbeam/example-plugin#32] opened 2024-01-31 18:44 UTC
Chat cannot be hidden anymore, and as another person said a few months ago, private messages are randomly going up and down sometimes

**Comment by hectorxn** [comment] 2024-01-31 23:42
Please somebody fix this, im too used to it now...

**Comment by LO0K0UT** [comment] 2024-02-01 05:37
I also am experiencing this issue. I love this plugin, and although it hasn't been updated in a long time. I really hope it gets support since it is now fully broken. 

It's an awesome viewing experience for the game in fixed mode.

**Comment by deathbeam** [comment] 2024-02-01 18:03
The main issue was solved, and rest is duplicate of https://github.com/deathbeam/example-plugin/issues/22, closing for now

**Comment by deathbeam** [comment] 2024-02-01 18:04
https://github.com/runelite/plugin-hub/pull/5469 here is PR waiting for approvalnot fixed in release yet

**Closed by deathbeam** 2024-02-01 18:03 UTC

**Comment by LemonAosi** [comment] 2024-02-01 18:50
> [runelite/plugin-hub#5469](https://github.com/runelite/plugin-hub/pull/5469) here is PR waiting for approvalnot fixed in release yet

Hi, does this mean the chat issue is fixed? I had tried installing the plugin and app but still not hiding the chat box - Is there something I have to do? or do I need to wait? Thanks :)

**Comment by deathbeam** [comment] 2024-02-01 18:59
> > [runelite/plugin-hub#5469](https://github.com/runelite/plugin-hub/pull/5469) here is PR waiting for approvalnot fixed in release yet
> 
> Hi, does this mean the chat issue is fixed? I had tried installing the plugin and app but still not hiding the chat box - Is there something I have to do? or do I need to wait? Thanks :)

It should be fixed now (like 1 min ago) so try to update the plugin or restart RL i guess
